{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "aa65ed0a-190a-4065-86ca-0c82608ea43f",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (2.0.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.9.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.25.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Requirement already satisfied: pandas-gbq in /opt/conda/lib/python3.10/site-packages (0.22.0)\n",
      "Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (69.5.1)\n",
      "Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (1.2.0)\n",
      "Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (1.25.2)\n",
      "Requirement already satisfied: pandas>=1.1.4 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (2.0.3)\n",
      "Requirement already satisfied: pyarrow>=3.0.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (15.0.2)\n",
      "Requirement already satisfied: pydata-google-auth>=1.5.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (1.8.2)\n",
      "Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (2.19.0)\n",
      "Requirement already satisfied: google-auth>=2.13.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (2.29.0)\n",
      "Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (1.2.0)\n",
      "Requirement already satisfied: google-cloud-bigquery<4.0.0dev,>=3.3.5 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (3.20.1)\n",
      "Requirement already satisfied: packaging>=20.0.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq) (24.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.63.0)\n",
      "Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.20.3)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.23.0)\n",
      "Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2.31.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from google-auth>=2.13.0->pandas-gbq) (5.3.3)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from google-auth>=2.13.0->pandas-gbq) (0.4.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.10/site-packages (from google-auth>=2.13.0->pandas-gbq) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)\n",
      "Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (2.4.1)\n",
      "Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (2.7.0)\n",
      "Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (2.9.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.1.4->pandas-gbq) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=1.1.4->pandas-gbq) (2024.1)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (1.62.1)\n",
      "Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (1.48.2)\n",
      "Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /opt/conda/lib/python3.10/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (1.5.0)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /opt/conda/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.13.0->pandas-gbq) (0.6.0)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0dev,>=2.7.2->google-cloud-bigquery<4.0.0dev,>=3.3.5->pandas-gbq) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (1.26.18)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core<3.0.0dev,>=2.10.2->pandas-gbq) (2024.2.2)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.2)\n",
      "Requirement already satisfied: seaborn in /opt/conda/lib/python3.10/site-packages (0.12.2)\n",
      "Requirement already satisfied: numpy!=1.24.0,>=1.17 in /opt/conda/lib/python3.10/site-packages (from seaborn) (1.25.2)\n",
      "Requirement already satisfied: pandas>=0.25 in /opt/conda/lib/python3.10/site-packages (from seaborn) (2.0.3)\n",
      "Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in /opt/conda/lib/python3.10/site-packages (from seaborn) (3.8.4)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.2.1)\n",
      "Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.12.1)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.51.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (24.0)\n",
      "Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.3.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.2)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.9.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.25->seaborn) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas>=0.25->seaborn) (2024.1)\n",
      "Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install pandas\n",
    "!pip install pandas-gbq\n",
    "!pip install seaborn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "26be0096-170b-4d99-b7cc-9912f40b4ad2",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/conda/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Table: tbl_maternity_pathway_antenatal, Source Rows: 36747, Target Rows: 36747\n",
      "Row counts match.\n",
      "Table: tbl_autism_amalgamated_ptl_oct2022, Source Rows: 6405, Target Rows: 6405\n",
      "Row counts match.\n",
      "Table: tbl_spell, Source Rows: 1735392, Target Rows: 1735392\n",
      "Row counts match.\n"
     ]
    }
   ],
   "source": [
    "from google.cloud import bigquery\n",
    "import pandas as pd\n",
    "import pandas_gbq\n",
    "\n",
    "# Initialize BigQuery client\n",
    "client = bigquery.Client(project=\"yhcr-prd-phm-bia-core\")\n",
    "\n",
    "# Databases\n",
    "source_db = \"yhcr-prd-phm-bia-core.CB_STAGING_DATABASE_WAREHOUSE_FDM_Format\"\n",
    "target_db = \"yhcr-prd-phm-bia-core.CB_MYSPACE_PAA\"\n",
    "\n",
    "# Specific tables to check\n",
    "tables_to_check = [\n",
    "    \"tbl_maternity_pathway_antenatal\",\n",
    "   \"tbl_autism_amalgamated_ptl_oct2022\",\n",
    "     \"tbl_spell\"\n",
    "]\n",
    "\n",
    "def get_row_count(dataset_id, table_name):\n",
    "    \"\"\"Returns the number of rows in the specified table.\"\"\"\n",
    "    query = f\"SELECT COUNT(*) as row_count FROM `{dataset_id}.{table_name}`\"\n",
    "    query_job = client.query(query)\n",
    "    results = query_job.result()\n",
    "    for row in results:\n",
    "        return row.row_count\n",
    "\n",
    "# Loop through each table and compare row counts\n",
    "for table in tables_to_check:\n",
    "    source_count = get_row_count(source_db, table)\n",
    "    target_count = get_row_count(target_db, table)\n",
    "    print(f\"Table: {table}, Source Rows: {source_count}, Target Rows: {target_count}\")\n",
    "    if source_count == target_count:\n",
    "        print(\"Row counts match.\")\n",
    "    else:\n",
    "        print(\"Row counts do not match.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c9971073-79a7-4021-96c3-2f9610f3a156",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/conda/lib/python3.10/site-packages/google/auth/_default.py:76: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a \"quota exceeded\" or \"API not enabled\" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds. \n",
      "  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Table: cb_PMH_MaternityDataset, Source Rows: 6093, Target Rows: 6093\n",
      "Row counts match.\n",
      "Table: cb_ae_detail, Source Rows: 5617410, Target Rows: 5617410\n",
      "Row counts match.\n",
      "Table: cb_episode_diagnosis, Source Rows: 9800742, Target Rows: 9800742\n",
      "Row counts match.\n",
      "Table: cb_episode_procedure, Source Rows: 2969016, Target Rows: 2969016\n",
      "Row counts match.\n",
      "Table: cb_maternity_delivery, Source Rows: 44828, Target Rows: 44828\n",
      "Row counts match.\n",
      "Table: cb_maternity_mother_child_relationship, Source Rows: 38428, Target Rows: 38428\n",
      "Row counts match.\n",
      "Table: cb_maternity_pathway_postnatal, Source Rows: 31134, Target Rows: 31134\n",
      "Row counts match.\n",
      "Table: cb_mother_child_relationship, Source Rows: 41606, Target Rows: 41606\n",
      "Row counts match.\n",
      "Table: cb_patient, Source Rows: 1240917, Target Rows: 1240917\n",
      "Row counts match.\n",
      "Table: cb_ward_lkp, Source Rows: 5626, Target Rows: 5626\n",
      "Row counts match.\n",
      "Table: lookup_ward, Source Rows: 5626, Target Rows: 5626\n",
      "Row counts match.\n",
      "Table: tbl_ae, Source Rows: 1961205, Target Rows: 1751776\n",
      "Row counts do not match.\n",
      "Table tbl_ae_detail does not exist in target database.\n",
      "Table: tbl_ae_investigation_nautilus, Source Rows: 8144479, Target Rows: 7668079\n",
      "Row counts do not match.\n",
      "Table: tbl_ae_nautilus, Source Rows: 837226, Target Rows: 736079\n",
      "Row counts do not match.\n",
      "Table: tbl_ae_timings_nautilus, Source Rows: 906953, Target Rows: 689030\n",
      "Row counts do not match.\n",
      "Table: tbl_ae_treatment_nautilus, Source Rows: 2872766, Target Rows: 2426396\n",
      "Row counts do not match.\n",
      "Table: tbl_apc_finished_susplus, Source Rows: 472273, Target Rows: 423926\n",
      "Row counts do not match.\n",
      "Table: tbl_autism_amalgamated_ptl_oct2022, Source Rows: 6405, Target Rows: 6405\n",
      "Row counts match.\n",
      "Table: tbl_critical_care_ICNARC_observation, Source Rows: 19776, Target Rows: 14924\n",
      "Row counts do not match.\n",
      "Table: tbl_critical_care_adult, Source Rows: 21744, Target Rows: 19875\n",
      "Row counts do not match.\n",
      "Table: tbl_critical_care_full_data_2015_2021, Source Rows: 13697, Target Rows: 13119\n",
      "Row counts do not match.\n",
      "Table: tbl_critical_care_neonatal, Source Rows: 6649, Target Rows: 2648\n",
      "Row counts do not match.\n",
      "Table: tbl_critical_care_neonatal_daily, Source Rows: 87997, Target Rows: 87997\n",
      "Row counts match.\n",
      "Table: tbl_ec_backward_compatible_susplus, Source Rows: 266786, Target Rows: 230771\n",
      "Row counts do not match.\n",
      "Table: tbl_episode, Source Rows: 2015939, Target Rows: 1865981\n",
      "Row counts do not match.\n",
      "Table: tbl_maternity_birth, Source Rows: 44985, Target Rows: 40675\n",
      "Row counts do not match.\n",
      "Table: tbl_maternity_care_plan, Source Rows: 41305, Target Rows: 40977\n",
      "Row counts do not match.\n",
      "Table: tbl_maternity_pathway_antenatal, Source Rows: 36747, Target Rows: 36568\n",
      "Row counts do not match.\n",
      "Table: tbl_maternity_pregnancy_and_booking_details, Source Rows: 15306, Target Rows: 15304\n",
      "Row counts do not match.\n",
      "Table tbl_meta does not exist in target database.\n",
      "Table: tbl_outpatient, Source Rows: 9081195, Target Rows: 8665218\n",
      "Row counts do not match.\n",
      "Table: tbl_outpatients_susplus, Source Rows: 1994629, Target Rows: 1890447\n",
      "Row counts do not match.\n",
      "Table: tbl_pharmacy, Source Rows: 2367730, Target Rows: 2292909\n",
      "Row counts do not match.\n",
      "Table: tbl_radiology, Source Rows: 4233986, Target Rows: 4065071\n",
      "Row counts do not match.\n",
      "Table: tbl_spell, Source Rows: 1735392, Target Rows: 1591326\n",
      "Row counts do not match.\n",
      "Table: tbl_theatre, Source Rows: 148456, Target Rows: 122421\n",
      "Row counts do not match.\n",
      "Table: tbl_ward_stay, Source Rows: 2916252, Target Rows: 2681116\n",
      "Row counts do not match.\n"
     ]
    }
   ],
   "source": [
    "# Check without using specific table names.\n",
    "from google.cloud import bigquery\n",
    "\n",
    "# Initialize BigQuery client\n",
    "client = bigquery.Client(project=\"yhcr-prd-phm-bia-core\")\n",
    "\n",
    "# Databases\n",
    "source_db = \"yhcr-prd-phm-bia-core.CB_STAGING_DATABASE_WAREHOUSE_FDM_Format\"\n",
    "target_db = \"yhcr-prd-phm-bia-core.CB_FDM_BradfordRoyalInfirmary\"\n",
    "\n",
    "def get_table_names(dataset_id):\n",
    "    \"\"\"Returns a list of table names in the given dataset.\"\"\"\n",
    "    tables = client.list_tables(dataset_id)\n",
    "    return [table.table_id for table in tables]\n",
    "\n",
    "def get_row_count(dataset_id, table_name):\n",
    "    \"\"\"Returns the number of rows in the specified table.\"\"\"\n",
    "    query = f\"SELECT COUNT(*) as row_count FROM `{dataset_id}.{table_name}`\"\n",
    "    query_job = client.query(query)\n",
    "    results = query_job.result()\n",
    "    for row in results:\n",
    "        return row.row_count\n",
    "\n",
    "# Get table names from source and target datasets\n",
    "source_tables = get_table_names(source_db)\n",
    "target_tables = get_table_names(target_db)\n",
    "\n",
    "# Loop through each table and compare row counts\n",
    "for table in source_tables:\n",
    "    if table in target_tables:\n",
    "        source_count = get_row_count(source_db, table)\n",
    "        target_count = get_row_count(target_db, table)\n",
    "        print(f\"Table: {table}, Source Rows: {source_count}, Target Rows: {target_count}\")\n",
    "        if source_count == target_count:\n",
    "            print(\"Row counts match.\")\n",
    "        else:\n",
    "            print(\"Row counts do not match.\")\n",
    "    else:\n",
    "        print(f\"Table {table} does not exist in target database.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e9eacf9c-9747-41cb-b332-28597e0f92ca",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "environment": {
   "kernel": "python3",
   "name": ".m120",
   "type": "gcloud",
   "uri": "us-docker.pkg.dev/deeplearning-platform-release/gcr.io/:m120"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
